# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55a8bb1e8d0b73a98cbeb81eb2187f7a3608c81322285b48fb204ec53e37f4ee397614f9bb5daa62d54cd478f8184ab95b34e8db26b4e58bd9c0110dba48cbbb

test:
  secret_key_base: a03b26b19b274fc81424a7378d225d85aabeb715bb5d00c2c14e1b88eaaad8f3bf817f8d650cc5079dedaa3b1f9b7864edb84e4e1095bd8a24003053d46b73cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
